version: "3.8"

services:
    api:
        ports:
            - 58080:8080
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: project
            POSTGRES_DB: projectdb
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_PASSWORD: redis_password

    postgres:
        ports:
            - 54320:5432
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: project
            POSTGRES_DB: projectdb

    pgadmin:
        ports:
            - 54330:80
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: password

    redis:
        ports:                  
            - "56379:6379"
        environment:
            REDIS_PASSWORD: redis_password
        command: redis-server --requirepass redis_password
