version: "3.8"

services:
    proxy:
        image: nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile.nginx

    api:
        build:
            context: ./api
            dockerfile: Dockerfile.api
        command: bash -c "./wait-for-it.sh postgres:5432 -t 12 -- ./wait-for-it.sh redis:6379 -t 10 -- /go/src/go-wave"

    postgres:
        image: postgres:13.2
        volumes:
            - ./db/sql/:/docker-entrypoint-initdb.d/
            - postgres_data:/var/lib/postgresql/data
    
    pgadmin:
        image: dpage/pgadmin4
        volumes:
            - pgadmin_data:/var/lib/pgadmin

    redis:
        image: "redis:alpine"
        volumes:
            - "redis_data:/data"


volumes:
    postgres_data:
    pgadmin_data:
    redis_data:
